const fakeDatabase = {
    "12": {
        isChronic: true,
        lastWhoVisited: {
                name: "Ruesina",
                surname: "Ciepo",
                occupation: "Anesthesiology",
                phone: "555 911 118",
                email: "doc@hospital.org",
        },
        firstName: "Goteorond",
        secondName: "Iorgwend",
        id: "12",
        age: 95,
        sex: "F",
        gender: "undefined",
        photo: null,
        bloodType: "0-",
        nextKin: "Varnëenil Taryawë",
        notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        lastAdmission: "22.01.2019",
        reasonOfVisit: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        treatment: "Bloodletting",
        address: "Rua do Catete 90, Glória, Rio de Janeiro - RJ",
    },
    "11": {
        isChronic: false,
        lastWhoVisited: {
                name: "Elros",
                surname: "Giliel",
                occupation: "Diagnostic Radiology ",
                phone: "555 911 118",
                email: "doc@hospital.org",
        },
        firstName: "Ceuariel",
        secondName: "Galadhhoaien",
        id: "11",
        age: 87,
        sex: "M",
        gender: "undefined",
        photo: null,
        bloodType: "A+",
        nextKin: "Hyartë Calmatanwen",
        notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        lastAdmission: "22.01.2019",
        reasonOfVisit: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        treatment: "Bloodletting",
        address: "Rua do Catete 90, Glória, Rio de Janeiro - RJ",
    },
    "141": {
        isChronic: true,
        lastWhoVisited: {
                name: "Celior",
                surname: "Iormea",
                occupation: "Neurology",
                phone: "555 911 118",
                email: "doc@hospital.org",
        },
        firstName: "Manarnon",
        secondName: "Úvaneamo",
        id: "141",
        age: 87,
        sex: "M",
        gender: "undefined",
        photo: null,
        bloodType: "AB",
        nextKin: "Parisse Nortarë",
        notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        lastAdmission: "22.01.2019",
        reasonOfVisit: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        treatment: "Bloodletting",
        address: "Rua do Catete 90, Glória, Rio de Janeiro - RJ",
    },
    "133": {
        isChronic: false,
        lastWhoVisited: {
                name: "Lúrëamë",
                surname: "Lórien",
                occupation: "Obstetrics",
                phone: "555 911 118",
                email: "doc@hospital.org",
        },
        firstName: "Lanatwen",
        secondName: "Húnamë",
        id: "133",
        age: 87,
        sex: "M",
        gender: "undefined",
        photo: null,
        bloodType: "A+",
        nextKin: "Liië Nucemenië",
        notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        lastAdmission: "22.01.2019",
        reasonOfVisit: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        treatment: "Bloodletting",
        address: "Rua do Catete 90, Glória, Rio de Janeiro - RJ",
    },
    "177": {
        isChronic: true,
        lastWhoVisited: {
                name: "Nercanis",
                surname: "Círë",
                occupation: "Ophthalmology",
                phone: "555 911 118",
                email: "doc@hospital.org",
        },
        firstName: "Erenwen",
        secondName: "Húnë",
        id: "177",
        age: 87,
        sex: "M",
        gender: "undefined",
        photo: null,
        bloodType: "A-",
        nextKin: "Elenyawen Arcien",
        notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        lastAdmission: "22.01.2019",
        reasonOfVisit: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        treatment: "Bloodletting",
        address: "Rua do Catete 90, Glória, Rio de Janeiro - RJ",
    },
    "232": {
        isChronic: true,
        lastWhoVisited: {
                name: "Miguel",
                surname: "Ribeiro de Almeida",
                occupation: "Clínico Geral",
                phone: "555 911 118",
                email: "doc@hospital.org",
        },
        firstName: "Antônio Carlos",
        secondName: "Jobim",
        id: "232",
        age: 87,
        sex: "M",
        gender: "undefined",
        photo: null,
        bloodType: "A-",
        nextKin: "Elenyawen Arcien",
        notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
        lastAdmission: "22.01.2019",
        reasonOfVisit: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
        treatment: "Bloodletting",
        address: "Rua do Catete 90, Glória, Rio de Janeiro - RJ",
    }
}

export async function getPatientsAPI(){
    await new Promise(resolve => setTimeout(resolve, 3000));
    return fakeDatabase;
}
export async function getPatientAPI(code){
    await new Promise(resolve => setTimeout(resolve, 2000));
    return fakeDatabase[code];
}